@RootCall = http://localhost:5223

GET {{RootCall}}/weatherforecast/
Accept: application/json

###

GET {{RootCall}}/api/FootballTeam
Accept: application/json

###
GET {{RootCall}}/api/FootballPlayer
Accept: application/json