@RootUrl = http://localhost:5232

###
GET {{RootUrl}}/api/FootballTeam
Accept: application/json

###
GET {{RootUrl}}/api/FootballPlayer
Accept: application/json

###
GET {{RootUrl}}/api/FootballTeam/1
Accept: application/json

###
GET {{RootUrl}}/api/Footballplayer/1
Accept: application/json

###
POST {{RootUrl}}/api/FootBallTeam
Content-Type: application/json
{
    "name": "Free Fire cars united",
    "yearFounded": 1976,
    "country": "Portugal",
    "manager": "Mr PL"
}

###
POST {{RootUrl}}/api/FootballPlayer
Content-Type: application/json
{
    "name": "Peter Alex andrews",
    "team": "DareDevil Fc",
    "age": 26,
    "nationality": "Swedish"
}

###
PUT {{RootUrl}}/api/FootballTeam/1
Content-Type: application/json
{
    "id": 1,
    "name": "Yuko warriors Rosethorn United",
    "yearFounded": 1945,
    "country": "France",
    "manager": "Mr wq"
}
###
PUT {{RootUrl}}/api/FootballPlayer/2
Content-Type: application/json
{
    "id": 2,
    "name": "Jimmy sandstorm",
    "team": "Astro Rovers",
    "age": 30,
    "nationality": "French/Polish"
}

###
DELETE {{RootUrl}}/api/FootballTeam/4

###
DELETE {{RootUrl}}/api/FootballPlayer/4