// <auto-generated />
using FootballApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250617150454_added_data")]
    partial class added_data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FootballApi.Models.FootballPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 23,
                            Name = "Dave Rogers",
                            Nationality = "Scottish",
                            Team = "Rushie United"
                        },
                        new
                        {
                            Id = 2,
                            Age = 30,
                            Name = "Jimmy Fred",
                            Nationality = "French",
                            Team = "Astro Rovers"
                        },
                        new
                        {
                            Id = 3,
                            Age = 27,
                            Name = "Roy Kollow",
                            Nationality = "Danish",
                            Team = "Red Warriors"
                        });
                });

            modelBuilder.Entity("FootballApi.Models.FootballTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manager")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearFounded")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "France",
                            Manager = "Mr T",
                            Name = "Yuko warriors",
                            YearFounded = 1945
                        },
                        new
                        {
                            Id = 2,
                            Country = "England",
                            Manager = "Mr Q",
                            Name = "Green Lamp United",
                            YearFounded = 1890
                        },
                        new
                        {
                            Id = 3,
                            Country = "Brazil",
                            Manager = "Mr Z",
                            Name = "Red Sea United",
                            YearFounded = 1956
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
